# Generated by Django 5.2.1 on 2025-05-18 20:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('domains', models.TextField(blank=True, null=True)),
                ('freshdesk_id', models.IntegerField(unique=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ativa', models.BooleanField(default=False, null=True)),
                ('l8security', models.BooleanField(default=False, null=True)),
                ('products', models.ManyToManyField(related_name='customers', to='product.product')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
