# Generated by Django 5.2.1 on 2025-05-19 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='month',
            new_name='date',
        ),
    ]
