# Generated by Django 5.2.1 on 2025-05-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='customer',
        ),
        migrations.AddField(
            model_name='communication',
            name='customer',
            field=models.ManyToManyField(related_name='communications', to='customer.customer'),
        ),
    ]
