# Generated by Django 5.2.1 on 2025-05-29 22:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_remove_communication_customer_communication_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communication',
            old_name='subject',
            new_name='alert_source',
        ),
        migrations.RenameField(
            model_name='communication',
            old_name='sent_at',
            new_name='date_end',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='communication_type',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='status',
        ),
        migrations.AddField(
            model_name='communication',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communication',
            name='description',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communication',
            name='impact_type',
            field=models.CharField(choices=[('altissimo', 'Altíssimo'), ('alto', 'Alto'), ('elevado', 'Elevado'), ('medio', 'Médio'), ('baixo', 'Baixo')], max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communication',
            name='incident_detail',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communication',
            name='incident_severity',
            field=models.CharField(choices=[('altissimo', 'Altíssimo'), ('alto', 'Alto'), ('elevado', 'Elevado'), ('medio', 'Médio'), ('baixo', 'Baixo')], max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communication',
            name='incident_treatment',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communication',
            name='notification_time',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communication',
            name='sent_by',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
